### ISSUE TITLE
interleavesound invalid frequencies

### ISSUE THREAD

**Issue by tjk584** [SuperDARNCanada/borealis_experiments#5]
Following error thrown when testing interleavesound:

```console
Traceback (most recent call last):
  File "/home/radar/borealis/tests/experiments/experiment_unittests.py", line 245, in test
    ehmain(experiment_name=module_name)
  File "/home/radar/borealis/tests/experiments/experiment_unittests.py", line 67, in ehmain
    exp = Experiment()
  File "/home/radar/borealis//src/borealis_experiments/interleavesound.py", line 91, in __init__
    self.add_slice(slices[1], {0: 'SCAN'})
  File "/home/radar/borealis//src/experiment_prototype/experiment_prototype.py", line 1136, in add_slice
    new_exp_slice = self.setup_slice(exp_slice)
  File "/home/radar/borealis//src/experiment_prototype/experiment_prototype.py", line 1825, in setup_slice
    self.check_slice_specific_requirements(complete_slice)
  File "/home/radar/borealis//src/experiment_prototype/experiment_prototype.py", line 1642, in check_slice_specific_requirements
    raise ExperimentException(errmsg)
experiment_prototype.experiment_exception.ExperimentException: freq must be a number (kHz) between tx min and max frequencies (9767.000012099743, 13267.000012099743) and rx min and max frequencies (9767.000012099743, 13267.000012099743) for the radar license and be within range given center frequencies (tx: 11517.000012099743 kHz, rx: 11517.000012099743 kHz), sampling rates (tx: 5000.0 kHz, rx: 5000.0 kHz), and transition band (750.0 kHz).
```

**Comment by KieranKuch** [comment]
Closing as stale. No longer relevant with auto rx/tx center frequencies.
